language: python

matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: osx
          language: generic
          env: PY_VER=2
        - os: osx
          language: generic
          env: PY_VER=3

# Perform the manual steps on osx to install python and activate venv
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip${PY_VER} install virtualenv; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv -p python${PY_VER} venv; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

# command to install dependencies
install:
  - export PIP_EXE=pip${PY_VER}
  - $PIP_EXE install pytest
  - $PIP_EXE install wheel
  - $PIP_EXE install --upgrade numpy
  - $PIP_EXE install -r requirements.txt
  - $PIP_EXE install .

# command to run tests
script:
  - pytest
  - python${PY_VER} setup.py bdist_wheel
