environment:
  matrix:

    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install pytest"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install ."

for:
  -
    skip_tags: true

build: off

test_script:
  # Test command
  - "%PYTHON%\\python.exe -m pytest"

after_test:
  # This step builds your wheels.
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

before_deploy:
  - "%PYTHON%\\python.exe setup.py --version > tempFile"
  - "set /p PKGVER= < tempFile"

deploy:
  tag: '$(PKGVER)'
  release: '$(PKGVER)'
  description: ''
  provider: GitHub
  auth_token:
    secure: lwJ/Q1SM5sDyCIzZbHRQAPzgJMCcEwDAi7tPU/OQRlbkp9kHtpHOLnLKC2L+c6Sf
  artifact: dist\*
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
